### ISSUE TITLE
作为videojs插件后似乎就无法监听flv.js对象所产生的各种事件了

### ISSUE THREAD

**Issue by JackyM06** [Yuliang-Lee/videojs-flvjs-es6#1]
作为videojs插件后似乎就无法监听flv.js对象所产生的各种事件了，是否能做一层委托，让开发者能够通过videojs的实例对象监听到flv.js的事件

**Comment by Yuliang-Lee** [comment]
可以反馈给 [video-js](https://github.com/mister-ben/videojs-flvjs)
